# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc477ce8b05a3523753963c043fd8ec9a5f22b01c1da88f6c90c8aa7aedf54172b43fd32acb90be5a5cabe2833c6f5d21a2a521e48cb7dcec7be38562da402d4

test:
  secret_key_base: 78fc3af7985d36a45f0c2d20e34e4f14bb47b76f555be4b44c5b5dcf9fc9140cd4238b2d695addfde4f08ae387856c8b846d03ed71c43ada79f2acf6131654b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
